### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by johnhce** [makeasnek/FindTheMag#2]
After running pip install -r C:\Users\John\Desktop\FindTheMag-master\requirements.txt
I get "Error: list index out of range"

I tried with the wallet running and with it shut down.  The wallet was unlocked for staking only.

Windows 7, 64-bit, python 3.8.7

**Comment by makeasnek** [comment]
Thank you for submitting a bug report and for trying out the tool! I just implemented a fix for this around the time you submitted the issue, can you please re-download the tool and try again? If it still happens, please e-mail me the full program output and a copy of your gridcoinresearch.conf (replace any sensitive content with XXXX) to makeasnek{at}gmail.com. I'll figure out why it's crashing on ya

**Comment by johnhce** [comment]
Here is the output from the latest version:
Guessing BOINC data dir is C:ProgramDataBOINCGuessing Gridcoin data
dir is C:UsersJohnAppDataRoamingGridcoinResearch
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Warning: Error parsing line from config file, ignoring:

Pase error was: list index out of range
Error: Gridcoin wallet is not configured to accept RPC commands based
on config
file from C:UsersJohnAppDataRoamingGridcoinResearch
RPC commands enable us to talk to the Gridcoin client and get
information about
project magnitude ratios
Would you like us to automatically configure your Gridcoin client to
accept RPC
commands?
It will be configured to only accept commands from your machine.
Please answer "Y" or "N" without quotes. Then press the enter key
Y
Your RPC username is: XXXXXX
Your RPC password is: XXXXXX
You don't need to remember these.
Modifying config file...
Alright, we've modified the config file. Please restart the gridcoin
wallet.
Once it's loaded and fully synced, press enter to continue

It appears that you have not enabled sidestaking to the Gridcoin
foundation in y
our wallet. We believe it is only fair that people benefiting from the
Gridcoin
network contribute back to it
Sidestaking enables you to contribute a small % of your staking
profits
This tool will not run unless you are donating at least 1% of your
staking earni
ngs to the Gridcoin foundation.
Would you like to enable sidestaking?.
Please answer "Y" or "N" (without quotes)
Y
What percent would you like to donate to the foundation? Donations go
towards so
ftware development, promotion, and growth of the coin. Enter a number
like 5 for
 5%. Please enter whole numbers only
1
Are you interested in sidestaking to the developers of this tool? This
is option
al. We ask you to consider what gain in efficiency this tool can bring
you and t
o donate a small portion of that gain.
Please. I am trying to buy a pony.
Please answer "Y" or "N" (without quotes)
Y
What percent would you like to donate to the developers of this tool?
Enter a nu
mber like 5 for 5%. Please enter whole numbers only
1
Welcome to FindTheMag and thank you for trying out this tool. Your
feedback and
suggestions are welcome on the github page : )
Looks like you are sidestaking to the foundation, thank you for giving
back!
Error getting project URL list from Gridcoin wallet. Are you sure it's
open? Err
or: can only concatenate str (not "int") to str

================

On 11/21/2021 at 6:56 PM, "makeasnek"  wrote:
	Thank you for submitting a bug report and for trying out the tool! I
just implemented a fix for this around the time you submitted the
issue, can you please re-download the tool and try again? If it still
happens, please e-mail me the full program output and a copy of your
gridcoinresearch.conf (replace any sensitive content with XXXX) to
makeasnek{at}gmail.com. I'll figure out why it's crashing on ya 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by makeasnek** [comment]
Aah thank you! It looks like it was having trouble parsing blank lines in the config file. I updated the code, can you try re-downloading and trying again? If it still gives you trouble, please e-mail a copy of your config file to makeasnek{at}gmail.com so I can figure out what's going on and get a fix in for it. You're probably not the only person having this problem.

**Comment by johnhce** [comment]
If set preferred_projects array to empty to get highest profit:

Highest mag/hr project is https://gene.disi.unitn.it/test/ w/ 0.0052882052712427
23/hr of credit
The following projects do not have enough stats to be calculated accurately, ass
igning them a weight of one:
['https://sech.me/boinc/amicable/',
 'https://boinc.thesonntags.com/collatz/',
 'https://www.cosmologyathome.org/',
 'https://einstein.phys.uwm.edu/',
 'https://milkyway.cs.rpi.edu/milkyway/',
 'https://minecraftathome.com/minecrafthome/',
 'https://escatter11.fullerton.edu/nfs/',
 'https://numberfields.asu.edu/numberfields/',
 'https://boinc.multi-pool.info/latinsquares/',
 'https://www.sidock.si/sidock/',
 'https://srbase.my-firewall.org/sr5/',
 'https://universeathome.pl/universe/',
 'https://www.worldcommunitygrid.org/boinc/',
 'https://www.rechenkraft.net/yoyo/']
Assigning 185.0 weight to 1 mining projects which means 185.0 per project
Traceback (most recent call last):
  File "main.py", line 762, in <module>
    per_preferred_project = total_preferred_weight / len(preferred_projects)
ZeroDivisionError: float division by zero

**Comment by makeasnek** [comment]
Aah thank you, I just removed that line completely as it's no longer needed. Pushed to github. Thank you for all the detailed bug reports, it's super useful for me! Just open a new one if it gives you any issues.
