### ISSUE TITLE
Windows instructions are incorrect

### ISSUE THREAD

**Issue by johnhce** [makeasnek/FindTheMag#3]
Windows quickstart instructions say:

In command prompt, run the command python install -r "C:\Users\user\Downloads\FindTheMag-master\requirements.txt" (or wherever you saved this tool)

This should be 

In command prompt, run the command pip install -r "C:\Users\user\Downloads\FindTheMag-master\requirements.txt" (or wherever you saved this tool)

**Comment by makeasnek** [comment]
You're absolutely right thank you for pointing this out, just updated the readme :)
